name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore fsEnsemble.sln
    - name: Build
      run: dotnet build fsEnsemble.sln --no-restore
    - name: Test
      run: dotnet test fsEnsemble.sln --no-build --verbosity normal
